[package]
version = "0.1.0"
name = "rsp"
edition = "2021"

[dependencies]
tokio.workspace = true
url.workspace = true
tracing-subscriber = "0.3.18"
dotenv = "0.15.0"
clap = { version = "4.5.7", features = ["derive", "env"] }
serde_json.workspace = true
serde.workspace = true
bincode = "1.3.3"
csv = "1.1"
lazy_static = "1.5.0"

# workspace
rsp-host-executor.workspace = true
rsp-client-executor.workspace = true

# alloy
alloy-provider.workspace = true

# reth 
reth-primitives.workspace = true

# sp1
# sp1-sdk = {version = "4.0.0", features = ["profiling"]}
sp1-sdk = { git = "https://github.com/succinctlabs/sp1-wip.git", branch = "yuwen/debug" }
sp1-core-executor = { git = "https://github.com/succinctlabs/sp1-wip.git", branch = "yuwen/debug" }

eyre = "0.6.12"
reqwest = "0.12.9"
base64 = "0.22.1"
hex = "0.4.3"
chrono = "0.4.39"
rkyv = "0.8.10"
sha2 = "0.10.8"

sp1-worker = { git = "https://github.com/succinctlabs/sp1-prover-service.git", branch = "yuwen/subblock" }
api2 = { git = "https://github.com/succinctlabs/sp1-prover-service.git", branch = "yuwen/subblock" }

# this is my latest aws-compatible branch
# sp1-worker = { git = "https://github.com/succinctlabs/sp1-prover-service.git", branch = "yuwen/aggregator"}
# sp1-worker = { path = "../../../sp1-prover-service/cluster/worker" }

[build-dependencies]
sp1-build = { git = "https://github.com/succinctlabs/sp1-wip.git", branch = "yuwen/debug" }

[[bin]]
name = "subblock"
path = "src/subblock.rs"

[[bin]]
name = "subblock-streaming"
path = "src/subblock-streaming.rs"

[features]
default = []
cuda = ["sp1-sdk/cuda"]
